### ISSUE TITLE
Strange transition on Chrome

### ISSUE THREAD

**Issue by vaiana** [fireship-io/222-responsive-icon-nav-css#4]
This works beautifully on FireFox but on Google Chrome when you unhover a link it first transitions to the black base color of the svg icon and then snaps to the gray color.  This also happens when you first hover the navbar, all the icons start in there base black color and then snap to gray. 

Any ideas on how to make it compatible with Chrome?

**Comment by b4ry** [comment]
@vaiana 
Hello. It seems to be working on my Chrome. Could you tell me what Chrome version you have as I cannot reproduce it?

**Comment by vaiana** [comment]
@b4ry right, I updated before I saw your comment and that fixed the problem.  Not sure the previous version but now it works perfect in Google Chrome 80.0.3987.122

Thanks!
